# Generated by Django 4.2.25 on 2025-11-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='houseNo',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phoneNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paymentmethod'),
        ),
    ]
