# Generated by Django 4.2.25 on 2025-11-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paymentmethod_remove_order_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shippingAddress',
        ),
    ]
