# Generated by Django 4.2.25 on 2025-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='houseNo',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
