# Generated by Django 4.2.25 on 2025-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shippingAddress',
            field=models.TextField(default=None),
        ),
    ]
