# Generated by Django 4.2.25 on 2025-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
