# Generated by Django 4.2.25 on 2025-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('totalSales', models.IntegerField()),
                ('revenue', models.ImageField(upload_to='')),
                ('numberOfOrders', models.IntegerField()),
            ],
        ),
    ]
