from django.urls import path
from app.views import (
    signupview,
    updateUser,
    loginview,
    logoutview,
    addproduct,
    userdetails,
    gender,
    updateProduct,
    deleteProduct,
    productDetails,
    productCategory,
    addtocart,
    removeFromCart,
    filterproduct,
    order,
    cartdata,
    salesInsights,
    downloadExcelData,
    orderdetails,
    payemntmethod,
    addcategory,
    email,

)


urlpatterns = [
    path("signup/", signupview),
    path("login/", loginview),
    path("updateuser/", updateUser),
    path("logout/", logoutview),
    path("addproduct/", addproduct),
    path("details/", userdetails),
    path("gender/", gender),
    path("payment/", payemntmethod),
    path("updateproduct/", updateProduct),
    path("deleteproduct/", deleteProduct),
    path("productdetails/", productDetails),
    path("productcategory/", productCategory),
    path("addproducts/", productCategory),
    path("addtocart/", addtocart),
    path("removefromcart/", removeFromCart),
    path("filter/", filterproduct),
    path('order/',order),
    path('orderdetails/',orderdetails),
    path('cartdata/',cartdata), 
    path('sales/', salesInsights),
    path('report/', downloadExcelData),
    path('addcategory/', addcategory),
     path('mail/', email),   
]
